"""
EXP-2 / EXP-6 independent SageMath certification.

Loads results/basis_23.json and verifies that each extracted law satisfies

    S_1 * Z_0 - S_0 * Z_1  ∈  (F(P), F(Q))
    S_2 * Z_0 - S_0 * Z_2  ∈  (F(P), F(Q))

by exact ideal membership. The reduction engine is Sage's own, which is
independent of the memoized substitution used by the Python extractor.

Usage:
    sage sage_verify.sage

Output:
    results/verification_sage.txt
"""


# This file was *autogenerated* from the file sage_verify.sage
from sage.all_cmdline import *   # import sage library

_sage_const_106839527430202782610735740077697524141755216002708025221579380756122101340723 = Integer(106839527430202782610735740077697524141755216002708025221579380756122101340723); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_60 = Integer(60); _sage_const_6 = Integer(6); _sage_const_9 = Integer(9); _sage_const_54 = Integer(54)
import json
import sys
from pathlib import Path

from sage.all import GF, PolynomialRing

HERE = Path(__file__).resolve().parent
RESULTS = HERE / "results"

P_MOD = _sage_const_106839527430202782610735740077697524141755216002708025221579380756122101340723 
U, V, W = _sage_const_5 , _sage_const_1 , _sage_const_7 

R = PolynomialRing(GF(P_MOD), names=("a", "b", "c", "x", "y", "z"))
a, b, c, x, y, z = R.gens()

F_P = U * a * (b**_sage_const_2  - c**_sage_const_2 ) + V * b * (c**_sage_const_2  - a**_sage_const_2 ) + W * c * (a**_sage_const_2  - b**_sage_const_2 )
F_Q = U * x * (y**_sage_const_2  - z**_sage_const_2 ) + V * y * (z**_sage_const_2  - x**_sage_const_2 ) + W * z * (x**_sage_const_2  - y**_sage_const_2 )
I = R.ideal([F_P, F_Q])

A = a * F_Q.derivative(x) + b * F_Q.derivative(y) + c * F_Q.derivative(z)
B = x * F_P.derivative(a) + y * F_P.derivative(b) + z * F_P.derivative(c)
R_0 = A * a - B * x
R_1 = A * b - B * y
R_2 = A * c - B * z
S_0 = R_1 * R_2
S_1 = R_2 * R_0
S_2 = R_0 * R_1

Q_P = [(_sage_const_2 , _sage_const_0 , _sage_const_0 ), (_sage_const_1 , _sage_const_1 , _sage_const_0 ), (_sage_const_1 , _sage_const_0 , _sage_const_1 ), (_sage_const_0 , _sage_const_2 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 , _sage_const_1 ), (_sage_const_0 , _sage_const_0 , _sage_const_2 )]
C_Q = [(_sage_const_0 , _sage_const_0 , _sage_const_3 ), (_sage_const_0 , _sage_const_1 , _sage_const_2 ), (_sage_const_0 , _sage_const_2 , _sage_const_1 ), (_sage_const_0 , _sage_const_3 , _sage_const_0 ),
       (_sage_const_1 , _sage_const_0 , _sage_const_2 ), (_sage_const_1 , _sage_const_1 , _sage_const_1 ), (_sage_const_1 , _sage_const_2 , _sage_const_0 ), (_sage_const_2 , _sage_const_0 , _sage_const_1 ), (_sage_const_3 , _sage_const_0 , _sage_const_0 )]


def mono_to_poly(m, vars):
    result = R(_sage_const_1 )
    for i, e in enumerate(m):
        if e:
            result *= vars[i] ** e
    return result


Q_P_polys = [mono_to_poly(m, (a, b, c)) for m in Q_P]
C_Q_polys = [mono_to_poly(m, (x, y, z)) for m in C_Q]


def main():
    with open(RESULTS / "basis_23.json") as f:
        data = json.load(f)

    lines = ["Sage independent verification of EXP-2/6 (2,3) basis",
             "=" * _sage_const_60 ]
    all_ok = True
    for law in data["laws"]:
        j = law["index"]
        coeffs = law["coeffs"]
        Z = [R(_sage_const_0 ), R(_sage_const_0 ), R(_sage_const_0 )]
        for i in range(_sage_const_3 ):
            for mu_idx in range(_sage_const_6 ):
                for nu_idx in range(_sage_const_9 ):
                    cc = int(coeffs[i * _sage_const_54  + mu_idx * _sage_const_9  + nu_idx]) % P_MOD
                    if cc:
                        Z[i] += cc * Q_P_polys[mu_idx] * C_Q_polys[nu_idx]

        G1 = S_1 * Z[_sage_const_0 ] - S_0 * Z[_sage_const_1 ]
        G2 = S_2 * Z[_sage_const_0 ] - S_0 * Z[_sage_const_2 ]
        ok1 = (G1 in I)
        ok2 = (G2 in I)
        ok = ok1 and ok2
        all_ok = all_ok and ok

        line = (f"law {j:02d}:  G1 in I = {ok1},  G2 in I = {ok2},  "
                f"overall = {ok}")
        print(line)
        lines.append(line)

    lines.append("=" * _sage_const_60 )
    lines.append(f"all certified: {all_ok}")
    (RESULTS / "verification_sage.txt").write_text("\n".join(lines) + "\n")

    print()
    print("\n".join(lines))
    return _sage_const_0  if all_ok else _sage_const_1 


if __name__ == "__main__":
    sys.exit(main())

